ALTER TABLE "user"
ADD COLUMN IF NOT EXISTS "banned" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "banReason" TEXT,
ADD COLUMN IF NOT EXISTS "banExpires" TIMESTAMP(6);

ALTER TABLE "session"
ADD COLUMN IF NOT EXISTS "impersonatedBy" TEXT;
